const { Players } = require('../models');

const playerData = [
  {
    player_name: 'Roy Kent',
    national_team: 'England',
    position: 'CM',
    kit_number: 6,
    date_of_birth: 'July 6',
    former_clubs: 'Sunderland AFC, Chelsea F.C.',
    games_played: 27,
    starts:27,
    goals:2,
    shots_on_target:11,
    assists: 2,
    passes_success_rate: .89,
    yellow_cards: 2,
    red_cards: 0,
    tackle_success_rate: .62,
    file_name: 'RoyKent.png'
  },
  {
    player_name: 'Dani Rojas',
    national_team: 'Mexico',
    position: 'ST',
    kit_number: 14,
    date_of_birth: 'September 16',
    former_clubs: 'Club America',
    games_played: 26,
    starts:26,
    goals:13,
    shots_on_target:32,
    assists: 5,
    passes_success_rate: .87,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: .54,
    file_name: 'Rojas.png'
  },
  {
    player_name: 'Jamie Tartt',
    national_team: 'England',
    position: 'ST',
    kit_number: 9,
    date_of_birth: 'May 1',
    former_clubs: 'Manchester City',
    games_played: 23,
    starts:21,
    goals:10,
    shots_on_target:23,
    assists: 1,
    passes_success_rate: .74,
    yellow_cards: 3,
    red_cards: 1,
    tackle_success_rate: .41,
    file_name: 'Tartt.png'
  },
  {
    player_name: 'Isaac McAdoo',
    national_team: 'England',
    position: 'CB',
    kit_number: 5,
    date_of_birth: 'June 4',
    former_clubs: 'Swansea',
    games_played: 27,
    starts:26,
    goals:0,
    shots_on_target:4,
    assists: 0,
    passes_success_rate: .88,
    yellow_cards: 0,
    red_cards: 0,
    tackle_success_rate: .63,
    file_name: 'McAdoo.png'
  },
  {
    player_name: 'Sam Obisanya',
    national_team: 'Nigeria',
    position: 'RB',
    kit_number: 24,
    date_of_birth: 'January 11',
    former_clubs: 'Enyimba F.C.',
    games_played: 24,
    starts:22,
    goals:4,
    shots_on_target:8,
    assists: 5,
    passes_success_rate: .79,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: .62,
    file_name: 'Obisanya.png'
  },
  {
    player_name: 'Colin Hughes',
    national_team: 'Wales',
    position: 'LW',
    kit_number: 12,
    date_of_birth: 'August 21',
    former_clubs: 'Cardiff',
    games_played: 26,
    starts:17,
    goals:2,
    shots_on_target:12,
    assists: 4,
    passes_success_rate: .77,
    yellow_cards: 0,
    red_cards: 0,
    tackle_success_rate: .33,
    file_name: 'Hughes.png'
  },
  {
    player_name: 'Jan Maas',
    national_team: 'Netherlands',
    position: 'CB',
    kit_number: 13,
    date_of_birth: 'January 23',
    former_clubs: 'FC Groningen',
    games_played: 16,
    starts:15,
    goals:0,
    shots_on_target:2,
    assists: 0,
    passes_success_rate: .87,
    yellow_cards: 8,
    red_cards: 0,
    tackle_success_rate: .69,
    file_name: 'Maas.png'
  },
  {
    player_name: 'Richard Montlaur',
    national_team: 'France',
    position: 'CM',
    kit_number: 8,
    date_of_birth: 'July 14',
    former_clubs: 'Newcastle United',
    games_played: 14,
    starts:9,
    goals:2,
    shots_on_target:5,
    assists: 3,
    passes_success_rate: .88,
    yellow_cards: 2,
    red_cards: 0,
    tackle_success_rate: .58,
    file_name: 'Montlaur.png'
  },
  {
    player_name: 'Thierry Zoreaux',
    national_team: 'Canada',
    position: 'GK',
    kit_number: 81,
    date_of_birth: 'July 1',
    former_clubs: 'Montreal F.C.',
    games_played: 29,
    starts:29,
    goals:0,
    shots_on_target:0,
    assists: 0,
    passes_success_rate: .76,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: .63,
    file_name: 'Zoreaux.png'
  },
  
];

const seedPlayers = () => Players.bulkCreate(playerData);

module.exports = seedPlayer;