const { Player } = require("../models");

const playerData = [
  {
    national_team: 'eng.png',
    position: "CM",
    kit_number: 6,
    date_of_birth: "July 6",
    former_clubs: "Sunderland AFC, Chelsea F.C.",
    games_played: 27,
    starts: 27,
    goals: 2,
    shots_on_target: 11,
    assists: 2,
    passes_success_rate: 0.89,
    yellow_cards: 2,
    red_cards: 0,
    tackle_success_rate: 0.62,
    file_name: "RoyKent.png",
    player_id: 1,
  },
  {
    national_team: 'mx.png',
    position: "ST",
    kit_number: 14,
    date_of_birth: "September 16",
    former_clubs: "Club America",
    games_played: 26,
    starts: 26,
    goals: 13,
    shots_on_target: 32,
    assists: 5,
    passes_success_rate: 0.87,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: 0.54,
    file_name: "Rojas.png",
    player_id: 2,
  },
  {
    national_team: 'eng.png',
    position: "ST",
    kit_number: 9,
    date_of_birth: "May 1",
    former_clubs: "Manchester City",
    games_played: 23,
    starts: 21,
    goals: 10,
    shots_on_target: 23,
    assists: 1,
    passes_success_rate: 0.74,
    yellow_cards: 3,
    red_cards: 1,
    tackle_success_rate: 0.41,
    file_name: "Tartt.png",
    player_id: 3,
  },
  {
    national_team: 'eng.png',
    position: "CB",
    kit_number: 5,
    date_of_birth: "June 4",
    former_clubs: "Swansea",
    games_played: 27,
    starts: 26,
    goals: 0,
    shots_on_target: 4,
    assists: 0,
    passes_success_rate: 0.88,
    yellow_cards: 0,
    red_cards: 0,
    tackle_success_rate: 0.63,
    file_name: "McAdoo.png",
    player_id: 4,
  },
  {
    national_team: 'ng.png',
    position: "RB",
    kit_number: 24,
    date_of_birth: "January 11",
    former_clubs: "Enyimba F.C.",
    games_played: 24,
    starts: 22,
    goals: 4,
    shots_on_target: 8,
    assists: 5,
    passes_success_rate: 0.79,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: 0.62,
    file_name: "Obisanya.png",
    player_id: 5,
  },
  {
    national_team: 'wls.png',
    position: "LW",
    kit_number: 12,
    date_of_birth: "August 21",
    former_clubs: "Cardiff",
    games_played: 26,
    starts: 17,
    goals: 2,
    shots_on_target: 12,
    assists: 4,
    passes_success_rate: 0.77,
    yellow_cards: 0,
    red_cards: 0,
    tackle_success_rate: 0.33,
    file_name: "Hughes.png",
    player_id: 6,
  },
  {
    national_team: 'nl.png',
    position: "CB",
    kit_number: 13,
    date_of_birth: "January 23",
    former_clubs: "FC Groningen",
    games_played: 16,
    starts: 15,
    goals: 0,
    shots_on_target: 2,
    assists: 0,
    passes_success_rate: 0.87,
    yellow_cards: 8,
    red_cards: 0,
    tackle_success_rate: 0.69,
    file_name: "Maas.png",
    player_id: 7,
  },
  {
    national_team: 'fr.png',
    position: "CM",
    kit_number: 8,
    date_of_birth: "July 14",
    former_clubs: "Newcastle United",
    games_played: 14,
    starts: 9,
    goals: 2,
    shots_on_target: 5,
    assists: 3,
    passes_success_rate: 0.88,
    yellow_cards: 2,
    red_cards: 0,
    tackle_success_rate: 0.58,
    file_name: "Montlaur.png",
    player_id: 8,
  },
  {
    national_team: 'ca.png',
    position: "GK",
    kit_number: 81,
    date_of_birth: "July 1",
    former_clubs: "Montreal F.C.",
    games_played: 29,
    starts: 29,
    goals: 0,
    shots_on_target: 0,
    assists: 0,
    passes_success_rate: 0.76,
    yellow_cards: 1,
    red_cards: 0,
    tackle_success_rate: 0.63,
    file_name: "Zoreaux.png",
    player_id: 9,
  },
];

const seedPlayers = () => Player.bulkCreate(playerData);

module.exports = seedPlayers;
